package com.cglia.authors.dto;

import java.sql.Date;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "umamahesh")
public class Author implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int authorId;
	private String authorName;
	private String authorAge;
	private Date aurhorBirthdate;
	private Set<Book> books = new HashSet<Book>();
	private AuthorBio authorBio;

	public Author() {
	}

	public Author(int authorId) {
		this.authorId = authorId;
	}

	public Author(int authorId, String authorName, String authorAge, Date aurhorBirthdate, Set<Book> books,
			AuthorBio authorBio) {
		this.authorId = authorId;
		this.authorName = authorName;
		this.authorAge = authorAge;
		this.aurhorBirthdate = aurhorBirthdate;
		this.books = books;
		this.authorBio = authorBio;
	}

	@Id

	@Column(name = "author_id", unique = true, nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "author_name", length = 45)
	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	@Column(name = "author_age", length = 45)
	public String getAuthorAge() {
		return this.authorAge;
	}

	public void setAuthorAge(String authorAge) {
		this.authorAge = authorAge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "aurhor_birthdate", length = 10)
	public Date getAurhorBirthdate() {
		return this.aurhorBirthdate;
	}

	public void setAurhorBirthdate(Date date) {
		this.aurhorBirthdate = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "author")
	public AuthorBio getAuthorBios() {
		return this.authorBio;
	}

	public void setAuthorBios(AuthorBio authorBios) {
		this.authorBio = authorBios;
	}

}
