package com.cglia.authors.dto;

//Generated 09-Jun-2023, 9:53:22 am by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Reader generated by hbm2java
 */
@Entity
@Table(name = "reader", catalog = "practice_jdbc")
public class Reader implements java.io.Serializable {

	private int readerId;
	private String readerName;
	private Integer readerAge;
	private Date buyedDate;
	@ManyToMany(mappedBy = "reader", fetch = FetchType.LAZY)
//	@JsonBackReference
	private Set<Book> books = new HashSet<>();

	public Reader() {
	}

	public Reader(int readerId) {
		this.readerId = readerId;
	}

	public Reader(int readerId, String readerName, Integer readerAge, Date buyedDate, Set<Book> book) {
		super();
		this.readerId = readerId;
		this.readerName = readerName;
		this.readerAge = readerAge;
		this.buyedDate = buyedDate;
		this.books = book;
	}

	public Set<Book> getBook() {
		return books;
	}

	public void setBook(Set<Book> book) {
		this.books = book;
	}

	@Id

	@Column(name = "reader_id", unique = true, nullable = false)
	public int getReaderId() {
		return this.readerId;
	}

	public void setReaderId(int readerId) {
		this.readerId = readerId;
	}

	@Column(name = "reader_name", length = 45)
	public String getReaderName() {
		return this.readerName;
	}

	public void setReaderName(String readerName) {
		this.readerName = readerName;
	}

	@Column(name = "reader_age")
	public Integer getReaderAge() {
		return this.readerAge;
	}

	public void setReaderAge(Integer readerAge) {
		this.readerAge = readerAge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "buyed_date", length = 10)
	public Date getBuyedDate() {
		return this.buyedDate;
	}

	public void setBuyedDate(Date buyedDate) {
		this.buyedDate = buyedDate;
	}
}
